### ISSUE TITLE
No header files generated

### ISSUE THREAD

**Issue by kowalski100** [polarfire-soc/polarfire-soc-configuration-generator#1]
I am using python-3 and **mpfs_configuration_generator.py** to generate header/c files. Following are my steps.

1. Generate XML file from MSS configurator
2. use python script to generate header files from XML files.

No error pops up and no files are generated as shown in figure below. [I tried to change directory but nothing happens].

 
![tmp](https://user-images.githubusercontent.com/7781522/127486896-ad431112-e3ea-465b-ac9f-9fe7c49dfe69.PNG)

**Comment by hughbreslin** [comment]
Hey @kowalski100 

This is working for me if I provide an output folder in the same directory as the script (it can't output into the directory its in):

    polarfire-soc-configuration-generator-master>python3 mpfs_configuration_generator.py test.xml ./output

With the following output

    fpga_config
    python interpreter details: sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
    python interpreter running is version 3
    Hardware configuration header files created in directory: /c/Users/M31864.MCHP-MAIN/Downloads/polarfire-soc-configuration-generator-master (1)/polarfire-soc-configuration-generator-master/output/fpga_config

**Comment by kowalski100** [comment]
Nope. I am on windows and even providing an output folder doesn't work for me.
I tried in different folder with no spaces in path. Still no luck. :(

![tmp](https://user-images.githubusercontent.com/7781522/127493372-a08d4e47-ec95-4e2a-9168-781bcf8e17b5.PNG)

**Comment by hughbreslin** [comment]
Hmm ok this is odd - to be honest I'm not sure and the script appears to be running correctly on my Windows machine. 

Would it be possible to add your updated XML to the softconsole project and see if it works when the script is called as part of the build process? In the project properties -> C/C++ Build -> Settings -> Build Steps the Python script is called to generate the header files (this uses the SoftConsole bundled Python):

![image](https://user-images.githubusercontent.com/44862881/127496128-2a7ad23f-f74f-40fb-a2fd-e16b6d9685c4.png)

Replacing the XML in the /src/boards/icicle-kit-es folder and building should then generate the header files for the bare metal project based on the updated XML you provided and then move on to build the project

**Comment by kowalski100** [comment]
Does the XML script needs to be added to HSS project or application project? As HSS does the necessary Multiplexing during boot time not the Application?

**Comment by hughbreslin** [comment]
If the application is being run as a HSS payload then the HSS needs the updated XML, if the application is being run through debug you should put the kit into boot mode 0 and add your XML to the application.

**Comment by nitindeshpande** [comment]
@kowalski100, Were you able to get the script working with the SoftConsole?

For the issue you saw with the command line, there are couple of points:
1. Path to a folder containing xml file or full path of the xml file need to be provided instead of just the xml filename.
2. The folder which is provided as the input where the xml file is stored, cannot be used as the output folder. 

We are planning to release improved version of the script with documentation this month. Hope that will help.
